### ISSUE TITLE
Help with completing the installation?

### ISSUE THREAD

**Issue by EightiesPower** [YuliangXiu/PuzzleAvatar#1]
So, I've been trying to set this up for the last couple of hours and after following the instructions to best of my ability, here are the errors that come up when I run run.sh: 

Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/multi_concepts/grounding_dino_sam.py", line 20, in <module>
    from groundingdino.util.inference import Model
ModuleNotFoundError: No module named 'groundingdino'
Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/multi_concepts/islands_all.py", line 9, in <module>
    import rpack
ModuleNotFoundError: No module named 'rpack'

Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/multi_concepts/train.py", line 62, in <module>
    import wandb
ModuleNotFoundError: No module named 'wandb'

Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/multi_concepts/inference.py", line 26, in <module>
    from peft import PeftModel
ModuleNotFoundError: No module named 'peft'

Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/cores/main_mc.py", line 12, in <module>
    from cores.lib.renderer import Renderer
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/cores/lib/renderer.py", line 6, in <module>
    import nvdiffrast.torch as dr
ModuleNotFoundError: No module named 'nvdiffrast'

Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/utils/body_utils/postprocess_mc.py", line 25, in <module>
    smplx_path = glob(smplx_paths)[0]
IndexError: list index out of range

Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/cores/main_mc.py", line 12, in <module>
    from cores.lib.renderer import Renderer
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/cores/lib/renderer.py", line 6, in <module>
    import nvdiffrast.torch as dr
ModuleNotFoundError: No module named 'nvdiffrast'

Now, I did install nvdiffrast. peft, and groundingdino. I've cloned each repository into the "thirdparties" folder and I've got groundingdino_swint_ogc and sam_vit_h_4b8939 in the PuzzleAvatar/weights folder. Can you tell what to install and where in order to move forward? Thank you.

**Comment by YuliangXiu** [comment]
Fixed, now you can `git clone --recurse-submodules git@github.com:YuliangXiu/PuzzleAvatar.git` to get all the submodules.

**Comment by gt732** [comment]
@YuliangXiu will this work on windows?

**Comment by YuliangXiu** [comment]
> @YuliangXiu will this work on windows?

I have not tested it on Windows, but it should work as long as you can setup the CUDA env.

**Comment by gt732** [comment]
> > @YuliangXiu will this work on windows?
> 
> I have not tested it on Windows, but it should work as long as you can setup the CUDA env.

I will give it a shot. Ty for your hard work on this. Do you know if using this library I can achieve what viggle ai does locally?

https://viggle.ai/m-home

Looks like they create a 3D mesh using the reference image, then apply the extracted mocap data to the avatar. I may be wrong though I’m new to this stuff.

Thanks!!

**Comment by EightiesPower** [comment]
> it clone --recurse-submodules git@github.com:YuliangXiu/PuzzleAvatar.git

Thanks for the response. I've done that and redid the Build modules section of the install guide. I'm still getting the following errors, however:

cat: OPENAI_API_KEY: No such file or directory
./scripts/env.sh: line 17: /home/yxiu/miniconda3/bin/activate: No such file or directory
Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/multi_concepts/grounding_dino_sam.py", line 20, in <module>
    from groundingdino.util.inference import Model
ModuleNotFoundError: No module named 'groundingdino'
Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/multi_concepts/islands_all.py", line 9, in <module>
    import rpack
ModuleNotFoundError: No module named 'rpack'
There was a problem when trying to write in your cache folder (/is/cluster/yxiu/.cache/hub). Please, ensure the directory exists and can be written to.
@torch.library.impl_abstract("xformers_flash::flash_bwd")
There was a problem when trying to write in your cache folder (/is/cluster/yxiu/.cache/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/multi_concepts/train.py", line 62, in <module>
    import wandb
ModuleNotFoundError: No module named 'wandb'
There was a problem when trying to write in your cache folder (/is/cluster/yxiu/.cache/hub). Please, ensure the directory exists and can be written to.
 @torch.library.impl_abstract("xformers_flash::flash_bwd")
There was a problem when trying to write in your cache folder (/is/cluster/yxiu/.cache/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/multi_concepts/inference.py", line 215, in <module>
    break_a_scene_inference = BreakASceneInference()
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/multi_concepts/inference.py", line 41, in __init__
    self._load_pipeline()
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/multi_concepts/inference.py", line 113, in _load_pipeline
    self.pipeline = DiffusionPipeline.from_pretrained(
  File "/home/eightiespower/miniconda3/envs/PuzzleAvatar/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/eightiespower/miniconda3/envs/PuzzleAvatar/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 719, in from_pretrained
    config_dict = cls.load_config(cached_folder)
  File "/home/eightiespower/miniconda3/envs/PuzzleAvatar/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/eightiespower/miniconda3/envs/PuzzleAvatar/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 373, in load_config
    raise EnvironmentError(
OSError: Error no file named model_index.json found in directory results/human/yuliang.
  @torch.cuda.amp.autocast(enabled=False)
Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/cores/main_mc.py", line 187, in <module>
    with open(json_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/yuliang/gpt4v_simple.json'
Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/utils/body_utils/postprocess_mc.py", line 25, in <module>
    smplx_path = glob(smplx_paths)[0]
IndexError: list index out of range
  @torch.cuda.amp.autocast(enabled=False)
Traceback (most recent call last):
  File "/media/eightiespower/01DB0091C59E37A0/AI_stuff/PuzzleAvatar/cores/main_mc.py", line 187, in <module>
    with open(json_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/yuliang/gpt4v_simple.json'

**Comment by EightiesPower** [comment]
For reference I'm attaching a .txt listing the contents of my thirdparties folder.
[thirdparties folder contents.txt](https://github.com/user-attachments/files/17059786/thirdparties.folder.contents.txt)

**Comment by EightiesPower** [comment]
I also had the following errors when running bash scripts/download_body_data.sh

Username/Password Authentication Failed.
Archive:  data/body_data/smpl_related/models/SMPL_python_v.1.0.0.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of data/body_data/smpl_related/models/SMPL_python_v.1.0.0.zip or
        data/body_data/smpl_related/models/SMPL_python_v.1.0.0.zip.zip, and cannot find data/body_data/smpl_related/models/SMPL_python_v.1.0.0.zip.ZIP, period.
mv: cannot stat 'data/body_data/smpl_related/models/smpl/models/basicModel_f_lbs_10_207_0_v1.0.0.pkl': No such file or directory
mv: cannot stat 'data/body_data/smpl_related/models/smpl/models/basicmodel_m_lbs_10_207_0_v1.0.0.pkl': No such file or directory

Downloading SMPLify...
--2024-09-19 13:45:31--  https://download.is.tue.mpg.de/download.php?domain=smplify&sfile=mpips_smplify_public_v2.zip&resume=1
Resolving download.is.tue.mpg.de (download.is.tue.mpg.de)... 192.124.27.139
Connecting to download.is.tue.mpg.de (download.is.tue.mpg.de)|192.124.27.139|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
Archive:  data/body_data/smpl_related/models/mpips_smplify_public_v2.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of data/body_data/smpl_related/models/mpips_smplify_public_v2.zip or
        data/body_data/smpl_related/models/mpips_smplify_public_v2.zip.zip, and cannot find data/body_data/smpl_related/models/mpips_smplify_public_v2.zip.ZIP, period.
mv: cannot stat 'data/body_data/smpl_related/models/smplify_public/code/models/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl': No such file or directory

Downloading SMPL-X...
--2024-09-19 13:45:32--  https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=models_smplx_v1_1.zip&resume=1
Resolving download.is.tue.mpg.de (download.is.tue.mpg.de)... 192.124.27.139
Connecting to download.is.tue.mpg.de (download.is.tue.mpg.de)|192.124.27.139|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
Archive:  data/body_data/smpl_related/models/models_smplx_v1_1.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of data/body_data/smpl_related/models/models_smplx_v1_1.zip or
        data/body_data/smpl_related/models/models_smplx_v1_1.zip.zip, and cannot find data/body_data/smpl_related/models/models_smplx_v1_1.zip.ZIP, period.

--2024-09-19 14:02:22--  http://./
Resolving . (.)... failed: No address associated with hostname.
wget: unable to resolve host address ‘.’

**Comment by gt732** [comment]
@EightiesPower I'm running through the installation as well. 

This is how you get rpack its under a different name

https://rectangle-packer.readthedocs.io/en/latest/_modules/rpack.html

**Comment by YuliangXiu** [comment]
> I also had the following errors when running bash scripts/download_body_data.sh
> 
> ```shell
> Username/Password Authentication Failed.
> Archive:  data/body_data/smpl_related/models/SMPL_python_v.1.0.0.zip
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> unzip:  cannot find zipfile directory in one of data/body_data/smpl_related/models/SMPL_python_v.1.0.0.zip or
>         data/body_data/smpl_related/models/SMPL_python_v.1.0.0.zip.zip, and cannot find data/body_data/smpl_related/models/SMPL_python_v.1.0.0.zip.ZIP, period.
> mv: cannot stat 'data/body_data/smpl_related/models/smpl/models/basicModel_f_lbs_10_207_0_v1.0.0.pkl': No such file or directory
> mv: cannot stat 'data/body_data/smpl_related/models/smpl/models/basicmodel_m_lbs_10_207_0_v1.0.0.pkl': No such file or directory
> 
> Downloading SMPLify...
> --2024-09-19 13:45:31--  https://download.is.tue.mpg.de/download.php?domain=smplify&sfile=mpips_smplify_public_v2.zip&resume=1
> Resolving download.is.tue.mpg.de (download.is.tue.mpg.de)... 192.124.27.139
> Connecting to download.is.tue.mpg.de (download.is.tue.mpg.de)|192.124.27.139|:443... connected.
> HTTP request sent, awaiting response... 401 Unauthorized
> 
> Username/Password Authentication Failed.
> Archive:  data/body_data/smpl_related/models/mpips_smplify_public_v2.zip
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> unzip:  cannot find zipfile directory in one of data/body_data/smpl_related/models/mpips_smplify_public_v2.zip or
>         data/body_data/smpl_related/models/mpips_smplify_public_v2.zip.zip, and cannot find data/body_data/smpl_related/models/mpips_smplify_public_v2.zip.ZIP, period.
> mv: cannot stat 'data/body_data/smpl_related/models/smplify_public/code/models/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl': No such file or directory
> 
> Downloading SMPL-X...
> --2024-09-19 13:45:32--  https://download.is.tue.mpg.de/download.php?domain=smplx&sfile=models_smplx_v1_1.zip&resume=1
> Resolving download.is.tue.mpg.de (download.is.tue.mpg.de)... 192.124.27.139
> Connecting to download.is.tue.mpg.de (download.is.tue.mpg.de)|192.124.27.139|:443... connected.
> HTTP request sent, awaiting response... 401 Unauthorized
> 
> Username/Password Authentication Failed.
> Archive:  data/body_data/smpl_related/models/models_smplx_v1_1.zip
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> unzip:  cannot find zipfile directory in one of data/body_data/smpl_related/models/models_smplx_v1_1.zip or
>         data/body_data/smpl_related/models/models_smplx_v1_1.zip.zip, and cannot find data/body_data/smpl_related/models/models_smplx_v1_1.zip.ZIP, period.
> 
> --2024-09-19 14:02:22--  http://./
> Resolving . (.)... failed: No address associated with hostname.
> wget: unable to resolve host address ‘.’
> ```

You should firstly register at [icon.is.tue.mpg.de](https://icon.is.tue.mpg.de/), following [register-at-icons-website](https://github.com/YuliangXiu/ICON/blob/master/docs/installation.md#register-at-icons-website), and input the username and password when you run the bash scripts.

**Comment by brinost** [comment]
```
Traceback (most recent call last):
  File "/root/PuzzleAvatar/cores/main_mc.py", line 259, in <module>
    model = Renderer(cfg)
  File "/root/PuzzleAvatar/cores/lib/renderer.py", line 150, in __init__
    self.dmtet_network.init_mesh(
  File "/root/PuzzleAvatar/cores/lib/dmtet_network.py", line 217, in init_mesh
    mesh_to_sdf.mesh_to_sdf(mesh,
  File "/root/miniconda3/lib/python3.10/site-packages/mesh_to_sdf/__init__.py", line 34, in mesh_to_sdf
    point_cloud = get_surface_point_cloud(mesh, surface_point_method, bounding_radius, scan_count, scan_resolution, sample_point_count, calculate_normals=sign_method=='normal')
  File "/root/miniconda3/lib/python3.10/site-packages/mesh_to_sdf/__init__.py", line 17, in get_surface_point_cloud
    return surface_point_cloud.create_from_scans(mesh, bounding_radius=bounding_radius, scan_count=scan_count, scan_resolution=scan_resolution, calculate_normals=calculate_normals)
  File "/root/miniconda3/lib/python3.10/site-packages/mesh_to_sdf/surface_point_cloud.py", line 162, in create_from_scans
    scans.append(Scan(mesh,
  File "/root/miniconda3/lib/python3.10/site-packages/mesh_to_sdf/scan.py", line 58, in __init__
    color, depth = render_normal_and_depth_buffers(mesh, camera, self.camera_transform, resolution)
  File "/root/miniconda3/lib/python3.10/site-packages/mesh_to_sdf/pyrender_wrapper.py", line 58, in render_normal_and_depth_buffers
    renderer = pyrender.OffscreenRenderer(resolution, resolution)
  File "/root/miniconda3/lib/python3.10/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/root/miniconda3/lib/python3.10/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/root/miniconda3/lib/python3.10/site-packages/pyrender/platforms/osmesa.py", line 19, in init_context
    from OpenGL.osmesa import (
ImportError: cannot import name 'OSMesaCreateContextAttribs' from 'OpenGL.osmesa' (/root/miniconda3/lib/python3.10/site-packages/OpenGL/osmesa/__init__.py)
Warp 1.5.1 initialized:
   CUDA Toolkit 12.6, Driver 12.4
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 4090" (24 GiB, sm_89, mempool enabled)
   Kernel cache:
     /root/.cache/warp/1.5.1
Traceback (most recent call last):
  File "/root/PuzzleAvatar/utils/body_utils/postprocess_mc.py", line 28, in <module>
    tech_obj = trimesh.load(tech_path, maintain_orders=True, process=False)
  File "/root/miniconda3/lib/python3.10/site-packages/trimesh/exchange/load.py", line 114, in load
    ) = _parse_file_args(file_obj=file_obj, file_type=file_type, resolver=resolver)
  File "/root/miniconda3/lib/python3.10/site-packages/trimesh/exchange/load.py", line 612, in _parse_file_args
    raise ValueError(f"string is not a file: {file_obj}")
ValueError: string is not a file: results/human/yuliang/obj/human_yuliang_geometry.obj
Warp 1.5.1 initialized:
   CUDA Toolkit 12.6, Driver 12.4
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 4090" (24 GiB, sm_89, mempool enabled)
   Kernel cache:
     /root/.cache/warp/1.5.1
Using prompt: a high-resolution DSLR colored image of a man, <asset0>  face, <asset1>  haircut, wearing <asset2>  coat, <asset3>  jeans, <asset4> brown bobble, <asset5> rainbow scarf, and <asset6>  shoes.
Using head prompt: a high-resolution DSLR colored image of a man, <asset0>  face, <asset1>  haircut, wearing <asset2>  coat, <asset3>  jeans, <asset4> brown bobble, <asset5> rainbow scarf, and <asset6>  shoes.
[load_obj] init empty albedo!
Traceback (most recent call last):
  File "/root/PuzzleAvatar/cores/main_mc.py", line 259, in <module>
    model = Renderer(cfg)
  File "/root/PuzzleAvatar/cores/lib/renderer.py", line 158, in __init__
    self.mesh = Mesh.load_obj(
  File "/root/PuzzleAvatar/cores/lib/obj.py", line 159, in load_obj
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results/human/yuliang/obj/human_yuliang_geometry_final.obj'
```
**I want to know isn`t it(results) empty first?**
