### ISSUE TITLE
Tensor size not match for down_cross attention

### ISSUE THREAD

**Issue by forseeking** [YuliangXiu/PuzzleAvatar#10]
Thank you for your excellent work. I encounter this problem when running the multi_concepts/train.py script with run.sh script provided. Here is the trace:

```bash
Traceback (most recent call last):
  File "/workspace/PuzzleAvatar/multi_concepts/train.py", line 1241, in <module>
    SpatialDreambooth()
  File "/workspace/PuzzleAvatar/multi_concepts/train.py", line 101, in __init__
    self.main()
  File "/workspace/PuzzleAvatar/multi_concepts/train.py", line 921, in main
    self.accelerator.backward(loss)
  File "/opt/conda/envs/PuzzleAvatar/lib/python3.10/site-packages/accelerate/accelerator.py", line 2241, in backward
    loss.backward(**kwargs)
  File "/opt/conda/envs/PuzzleAvatar/lib/python3.10/site-packages/torch/_tensor.py", line 581, in backward
    torch.autograd.backward(
  File "/opt/conda/envs/PuzzleAvatar/lib/python3.10/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/opt/conda/envs/PuzzleAvatar/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/envs/PuzzleAvatar/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1125, in unpack_hook
    frame.recompute_fn(*args)
  File "/opt/conda/envs/PuzzleAvatar/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1519, in recompute_fn
    fn(*args, **kwargs)
  File "/opt/conda/envs/PuzzleAvatar/lib/python3.10/site-packages/diffusers/models/transformers/transformer_2d.py", line 425, in custom_forward
    return module(*inputs)
  File "/opt/conda/envs/PuzzleAvatar/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/PuzzleAvatar/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/PuzzleAvatar/lib/python3.10/site-packages/diffusers/models/attention.py", line 545, in forward
    attn_output = self.attn2(
  File "/opt/conda/envs/PuzzleAvatar/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/PuzzleAvatar/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/PuzzleAvatar/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 495, in forward
    return self.processor(
  File "/workspace/PuzzleAvatar/multi_concepts/ptp_utils.py", line 60, in __call__
    self.controller(attention_probs, is_cross, self.place_in_unet)
  File "/workspace/PuzzleAvatar/multi_concepts/ptp_utils.py", line 150, in __call__
    self.between_steps()
  File "/workspace/PuzzleAvatar/multi_concepts/ptp_utils.py", line 195, in between_steps
    self.attention_store[key][i] += self.step_store[key][i]
RuntimeError: The size of tensor a (1024) must match the size of tensor b (256) at non-singleton dimension 1

```

I tried the following debug code:
```python
  print(key)
  print(f"attention_store shape: {self.attention_store[key][i].shape}")
  print(f"step_store shape: {self.step_store[key][i].shape}")    
```
Output:
```python
down_cross
attention_store shape: torch.Size([40, 1024, 77])
step_store shape: torch.Size([80, 256, 77])
```

**Comment by Niu0914** [comment]
same question

**Comment by xdobetter** [comment]
This is caused by --set_grads_to_none, and a simple solution is to comment it out.
In scripts/run.sh  52 line
```
# --set_grads_to_none
```

**Comment by YuliangXiu** [comment]
About the setting of `set_grads_to_none`:
- https://pytorch.org/docs/stable/generated/torch.optim.Optimizer.zero_grad.html
- https://huggingface.co/docs/diffusers/v0.20.0/en/training/custom_diffusion

**Comment by Niu0914** [comment]
This parameter in the train. 934 lines of py is used, but an error occurred in the self. The accelerator. The backward (loss) (line 920), if other reason causes this error? In fact, I commented out set_grads_to_none and the error still occurred

**Comment by Niu0914** [comment]
-- set_grads_to_none is used in the train. py 934 line, but the error occurred in' self. The accelerator. The backward (loss) ' (line 920), if other reason causes this error? In fact, I commented out set_grads_to_none and the error still occurred

**Comment by xdobetter** [comment]
> -- set_grads_to_none is used in the train. py 934 line, but the error occurred in' self. The accelerator. The backward (loss) ' (line 920), if other reason causes this error? In fact, I commented out set_grads_to_none and the error still occurred

Hello~ I speculate the primary issue arises from VRAM optimization techniques; I just utilized the latest code and discovered that it should be capable of functioning properly. There is no issue with commenting out the entire section, and anyone encountering this matter can verify it again.

In scripts/run.sh 49-52.
```bash
  # --gradient_checkpointing \
  # --mixed_precision fp16 \
  # --use_8bit_adam \
  # --set_grads_to_none \
```

**Comment by Niu0914** [comment]
Thank you. It's working now  ̋(๑˃́ꇴ˂̀๑) !
